# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 08:01
from __future__ import unicode_literals

from django.db import migrations


def create_default_tests(apps, schema_editor):
    model = apps.get_registered_model("dashboard", "FacilityTest")
    model.objects.filter(name_in=["Facility Reporting", "GUIDELINE ADHERENCE (Adult 1L)"]).update(featured=True)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0037_auto_20180201_1935'),
    ]

    operations = [
        migrations.RunPython(create_default_tests, reverse),
    ]
